BASE_URL = "https://stellarburgers.education-services.ru"
REGISTER_USER = f"{BASE_URL}/api/auth/register"
LOGIN_USER = f"{BASE_URL}/api/auth/login"
DELETE_USER = f"{BASE_URL}/api/auth/user"
INGREDIENTS = f"{BASE_URL}/api/ingredients"
ORDERS = f"{BASE_URL}/api/orders"
